---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: ospf
  connection: network_cli
  gather_facts: no

  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output